language: ruby
bundler_args: --without development
before_install:
  - git submodule update --init --recursive
script: "bundle exec rake build_ci"
rvm:
  - 2.1.1
gemfile:
  - Gemfile
branches:
  only:
    - master
    - develop
